mode.production: true

app.name: "user-vault"

mysql:
  enabled: true
  user: "${MYSQL_USERNAME}"
  password: "${MYSQL_PASSWORD}"
  database: "authserver"
  host: "${MYSQL_HOST}"
  port: 3306

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

rabbitmq:
  enabled: true
  host: "${RABBITMQ_ADDR}"
  port: 5672
  username: "${RABBITMQ_USERNAME}"
  password: "${RABBITMQ_PASSWORD}"
  vhost: "/"

server:
  host: "0.0.0.0"
  port: 8089

consul:
  enabled: true
  consulAddress: "${CONSUL_HOST}:8500"

logging.rolling.file: "/usr/src/logs/${app.name}.log"

jwt:
  key:
    public: ${jwt.publicKey}
    private: ${jwt.privateKey}
    issuer: ${jwt.issuer}

monitor:
  - service: "logbot"
  - service: "vfm"
  - service: "fstore"
  - service: "acct"