mode.production: true

app.name: "user-vault"

mysql:
  enabled: true
  user: "${mysqlusername}"
  password: "${mysqlpassword}"
  database: "authserver"
  host: "${mysqladdr}"
  port: 3306

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

rabbitmq:
  enabled: true
  host: "rabbitmq"
  port: 5672
  username: "${rabbitmqusername}"
  password: "${rabbitmqpassword}"
  vhost: "/"

server:
  host: "0.0.0.0"
  port: 8089

consul:
  enabled: true
  consulAddress: consul:8500
  healthCheckUrl: /health

logging.rolling.file: "/usr/src/logs/${app.name}.log"

goauth.client.enabled: true

jwt:
  key:
    public: ${jwt-module.publicKey}
    private: ${jwt-module.privateKey}
    issuer: "yongj.zhuang-auth-service"

